# Generated by Django 5.0.4 on 2024-07-23 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='conbustible',
            field=models.CharField(default='Gasolina', max_length=50),
        ),
        migrations.AddField(
            model_name='auto',
            name='pais_fabricacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='puertas',
            field=models.CharField(default='4', max_length=100),
        ),
        migrations.AddField(
            model_name='modeloauto',
            name='anio',
            field=models.CharField(default='2020', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='accesorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.accesorio'),
        ),
    ]
