# Generated by Django 5.0.4 on 2024-07-24 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_conbustible_auto_pais_fabricacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='accesorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.accesorio'),
        ),
    ]
