# Generated by Django 5.0.3 on 2024-07-25 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_venta_accesorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='puertas',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='modeloauto',
            name='anio',
            field=models.CharField(default='2020', max_length=4),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='accesorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.accesorio'),
        ),
    ]
