# Generated by Django 5.0.4 on 2024-08-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_accesorio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='is_staff_user',
            field=models.BooleanField(default=False),
        ),
    ]
