# Generated by Django 5.0.4 on 2024-08-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_comentario_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='user',
            new_name='cliente',
        ),
    ]
