# Generated by Django 5.0.4 on 2024-08-07 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_rename_user_cita_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.cliente'),
        ),
    ]
