# Generated by Django 5.0.4 on 2024-08-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_empleado_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
