# Generated by Django 5.0.4 on 2024-10-03 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='conbustible',
        ),
        migrations.AddField(
            model_name='auto',
            name='combustible',
            field=models.CharField(default='Gasolina', max_length=50, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='autos',
            field=models.ManyToManyField(related_name='accesorios', to='cars.auto', verbose_name='Autos'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='accesorios/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(upload_to='autos/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.modeloauto', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='pais_fabricacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País de fabricación'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='puertas',
            field=models.IntegerField(default=4, verbose_name='Puertas'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.servicio', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='is_staff_user',
            field=models.BooleanField(default=False, verbose_name='Es usuario staff'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto', verbose_name='Auto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empleados/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='puesto',
            field=models.CharField(max_length=100, verbose_name='Puesto'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='modeloauto',
            name='anio',
            field=models.CharField(default='2020', max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='modeloauto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='modeloauto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='autos',
            field=models.ManyToManyField(to='cars.auto', verbose_name='Autos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='accesorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.accesorio', verbose_name='Accesorio'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auto', verbose_name='Auto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio_final',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio final'),
        ),
    ]
